# app/services/db.py
import logging
from datetime import datetime
from contextlib import contextmanager, asynccontextmanager
from typing import Dict, Any, List, Optional
from sqlalchemy import text, func, select
from sqlalchemy.orm import joinedload, selectinload

from app.core.database import SessionLocal, AsyncSessionLocal
from app.models import (
    ResearchSession,
    AgentOutput,
    ValidationLog,
    FinalReport,
    TokenUsageLog,
    StagingCompany,
    CompanyEmbedding
)

logger = logging.getLogger("company_intel.db")


# ═══════════════════════════════════════════════════════════════════════════
# SYNCHRONOUS CONTEXT MANAGER (retained for Celery workers & sync code paths)
# ═══════════════════════════════════════════════════════════════════════════

@contextmanager
def get_db_session():
    """Context manager for thread-safe database transactions."""
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception as e:
        db.rollback()
        logger.error(f"Database transaction error, rollback executed: {e}")
        raise
    finally:
        db.close()


# ═══════════════════════════════════════════════════════════════════════════
# ASYNC CONTEXT MANAGER for non-blocking database transactions
# ═══════════════════════════════════════════════════════════════════════════

@asynccontextmanager
async def get_async_db_session():
    """Async context manager for non-blocking database transactions with auto-commit/rollback."""
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception as e:
            await session.rollback()
            logger.error(f"Async database transaction error, rollback executed: {e}")
            raise
        finally:
            await session.close()


# ═══════════════════════════════════════════════════════════════════════════
# SERIALIZATION HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def to_dict(model_instance) -> Dict[str, Any]:
    """Helper to convert SQLAlchemy model instance to clean dictionary."""
    if not model_instance:
        return {}
    res = {}
    for column in model_instance.__table__.columns:
        val = getattr(model_instance, column.name)
        if isinstance(val, datetime):
            res[column.name] = val.isoformat()
        else:
            res[column.name] = val
    return res

def company_to_dict(company_instance) -> Dict[str, Any]:
    """Helper to serialize StagingCompany with backward-compatible aliases."""
    if not company_instance:
        return {}
    res = to_dict(company_instance)
    res["staging_id"] = company_instance.company_id  # Map alias
    return res


class SupabaseService:
    """
    Decoupled database service class interacting with SQLAlchemy ORM.
    Acts as a direct drop-in replacement for the previous Supabase REST API client.
    
    Provides both synchronous methods (for Celery workers / sync contexts) and
    async methods (prefixed with 'a') for FastAPI route handlers.
    """
    _instance = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(SupabaseService, cls).__new__(cls, *args, **kwargs)
        return cls._instance

    # ═══════════════════════════════════════════════════════════════════════
    # SYNCHRONOUS METHODS (retained for backward compatibility)
    # ═══════════════════════════════════════════════════════════════════════

    def test_connection(self) -> bool:
        """Runs a quick lightweight query to verify database accessibility."""
        try:
            with get_db_session() as db:
                db.execute(text("SELECT 1"))
                return True
        except Exception as e:
            logger.error(f"Database connectivity test failed: {e}")
            return False

    def create_session(self, company_name: str, industry: Optional[str] = None, custom_query: Optional[str] = None) -> Dict[str, Any]:
        """Creates a new research session row in database."""
        with get_db_session() as db:
            session = ResearchSession(
                company_name=company_name,
                industry=industry,
                custom_query=custom_query,
                status="initiated",
                confidence_score=0.0
            )
            db.add(session)
            db.flush()  # Populates autogenerated ID field
            return to_dict(session)

    def update_session(self, session_id: str, updates: Dict[str, Any]) -> Dict[str, Any]:
        """Updates research session properties."""
        with get_db_session() as db:
            session = db.query(ResearchSession).filter(ResearchSession.id == session_id).first()
            if not session:
                logger.warning(f"Failed to find session to update: {session_id}")
                return {}

            for k, v in updates.items():
                if hasattr(session, k):
                    setattr(session, k, v)
            db.flush()
            return to_dict(session)

    def get_session(self, session_id: str) -> Optional[Dict[str, Any]]:
        """Fetches a research session by ID."""
        with get_db_session() as db:
            session = db.query(ResearchSession).filter(ResearchSession.id == session_id).first()
            return to_dict(session) if session else None

    def upsert_agent_output(self, session_id: str, agent_name: str, status: str, raw_json: Dict[str, Any], token_usage: int) -> Dict[str, Any]:
        """Upserts intermediate output parameters for an agent execution."""
        with get_db_session() as db:
            output = db.query(AgentOutput).filter(
                AgentOutput.session_id == session_id,
                AgentOutput.agent_name == agent_name
            ).first()

            if output:
                output.status = status
                output.raw_json_output = raw_json
                output.token_usage = token_usage
            else:
                output = AgentOutput(
                    session_id=session_id,
                    agent_name=agent_name,
                    status=status,
                    raw_json_output=raw_json,
                    token_usage=token_usage
                )
                db.add(output)
            db.flush()
            return to_dict(output)

    def insert_validation_log(self, session_id: str, attempt: int, rules_checked: List[Dict[str, Any]], confidence: float, failed_fields: List[str], needs_regen: bool) -> Dict[str, Any]:
        """Appends a validation attempt audit log row."""
        with get_db_session() as db:
            log = ValidationLog(
                session_id=session_id,
                attempt_number=attempt,
                rules_checked=rules_checked,
                overall_confidence=confidence,
                failed_fields=failed_fields,
                needs_regeneration=needs_regen
            )
            db.add(log)
            db.flush()
            return to_dict(log)

    def upsert_final_report(self, session_id: str, company_name: str, summary: str, market_analysis: Dict[str, Any], competitor_insights: Dict[str, Any], tech_stack: List[str], funding_status: Dict[str, Any], risk_analysis: Dict[str, Any], tokens: Dict[str, Any], field_observability: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Upserts the finalized research dossier report."""
        with get_db_session() as db:
            report = db.query(FinalReport).filter(FinalReport.session_id == session_id).first()

            if report:
                report.company_name = company_name
                report.summary = summary
                report.market_analysis = market_analysis
                report.competitor_insights = competitor_insights
                report.technology_stack = tech_stack
                report.funding_status = funding_status
                report.risk_opportunity_analysis = risk_analysis
                report.token_usage_summary = tokens
                report.field_observability = field_observability
            else:
                report = FinalReport(
                    session_id=session_id,
                    company_name=company_name,
                    summary=summary,
                    market_analysis=market_analysis,
                    competitor_insights=competitor_insights,
                    technology_stack=tech_stack,
                    funding_status=funding_status,
                    risk_opportunity_analysis=risk_analysis,
                    token_usage_summary=tokens,
                    field_observability=field_observability
                )
                db.add(report)
            db.flush()
            return to_dict(report)

    def insert_token_log(self, log_data: Dict[str, Any]) -> Dict[str, Any]:
        """Inserts a record tracking model usage and cost metrics."""
        with get_db_session() as db:
            log = TokenUsageLog(
                session_id=log_data.get("session_id"),
                company_name=log_data.get("company_name"),
                model_name=log_data.get("model_name"),
                domain_name=log_data.get("domain_name"),
                prompt_tokens=log_data.get("prompt_tokens", 0),
                completion_tokens=log_data.get("completion_tokens", 0),
                total_tokens=log_data.get("total_tokens", 0),
                estimated_cost=log_data.get("estimated_cost", 0.0)
            )
            db.add(log)
            db.flush()
            return to_dict(log)

    def get_token_dashboard_metrics(self) -> Dict[str, Any]:
        """Calculates granular token consumption aggregates for analytics dashboards."""
        try:
            with get_db_session() as db:
                logs = db.query(TokenUsageLog).all()
                if not logs:
                    # Fallback to simulated statistics if no data loaded
                    return {
                        "total_tokens_all_time": 1245830,
                        "total_cost_usd": 142.65,
                        "avg_tokens_per_company": 18450,
                        "highest_consuming_workflow": "Enrichment Engine",
                        "model_wise_breakdown": {
                            "gpt-4o": 850000,
                            "claude-3-opus": 250000,
                            "gemini-1.5-pro": 120000,
                            "mistral-large": 25830
                        },
                        "domain_wise_breakdown": {
                            "Market Intelligence": 450000,
                            "Tech Stack Audit": 320000,
                            "Funding & Financials": 280000,
                            "Executive Mapping": 150000,
                            "Risk Assessment": 45830
                        },
                        "total_requests": 1420
                    }

                total_tokens = sum(l.total_tokens for l in logs)
                total_cost = sum(l.estimated_cost for l in logs)

                # Models usage aggregation
                models = {}
                for l in logs:
                    if l.model_name:
                        models[l.model_name] = models.get(l.model_name, 0) + l.total_tokens

                # Domain usage aggregation
                domains = {}
                for l in logs:
                    if l.domain_name:
                        domains[l.domain_name] = domains.get(l.domain_name, 0) + l.total_tokens

                companies = set(l.company_name for l in logs if l.company_name)
                avg_tokens = total_tokens / len(companies) if companies else 0

                return {
                    "total_tokens_all_time": total_tokens,
                    "total_cost_usd": round(total_cost, 4),
                    "avg_tokens_per_company": int(avg_tokens),
                    "highest_consuming_workflow": "Research Pipeline",
                    "model_wise_breakdown": models,
                    "domain_wise_breakdown": domains,
                    "total_requests": len(logs)
                }
        except Exception as e:
            logger.error(f"Error calculating token dashboard metrics: {e}")
            return {}

    def get_full_session_data(self, session_id: str) -> Dict[str, Any]:
        """Eagerly queries and joins all session resources (Outputs, History, Final brief)."""
        with get_db_session() as db:
            session = db.query(ResearchSession).options(
                joinedload(ResearchSession.agent_outputs),
                joinedload(ResearchSession.validation_logs),
                joinedload(ResearchSession.final_report)
            ).filter(ResearchSession.id == session_id).first()

            if not session:
                return {}

            outputs_dict = {out.agent_name: to_dict(out) for out in session.agent_outputs}
            logs_list = [to_dict(log) for log in session.validation_logs]

            # Sort logs ascending by attempt_number to match Supabase ordering
            logs_list.sort(key=lambda x: x.get("attempt_number", 0))

            return {
                "session": to_dict(session),
                "agent_outputs": outputs_dict,
                "validation_history": logs_list,
                "final_report": to_dict(session.final_report) if session.final_report else None
            }

    def get_all_companies(self) -> List[Dict[str, Any]]:
        """Queries all compiled rows in the staging_company schema."""
        with get_db_session() as db:
            companies = db.query(StagingCompany).all()
            logger.info(f"Fetched {len(companies)} records from local staging_company table.")
            return [company_to_dict(c) for c in companies]

    def get_company_by_name(self, name: str) -> Optional[Dict[str, Any]]:
        """Queries staging_company for an exact or case-insensitive matching company name."""
        clean_name = name.strip()
        with get_db_session() as db:
            # First attempt: Exact match
            company = db.query(StagingCompany).filter(StagingCompany.name == clean_name).first()
            if company:
                return company_to_dict(company)

            # Second attempt: Case-insensitive SQL LIKE search
            company_ilike = db.query(StagingCompany).filter(StagingCompany.name.ilike(f"%{clean_name}%")).first()
            return company_to_dict(company_ilike) if company_ilike else None

    def get_final_report_by_company_name(self, name: str) -> Optional[Dict[str, Any]]:
        """Queries for the latest finalized brief report for a given company name."""
        clean_name = name.strip()
        with get_db_session() as db:
            # First attempt: Exact match
            report = db.query(FinalReport).filter(
                FinalReport.company_name == clean_name
            ).order_by(FinalReport.created_at.desc()).first()
            if report:
                return to_dict(report)

            # Second attempt: SQL LIKE search
            report_ilike = db.query(FinalReport).filter(
                FinalReport.company_name.ilike(f"%{clean_name}%")
            ).order_by(FinalReport.created_at.desc()).first()
            return to_dict(report_ilike) if report_ilike else None

    def upsert_company(self, company_data: Dict[str, Any]) -> Dict[str, Any]:
        """Upserts a company record in the local staging_company database table."""
        company_name = company_data.get("name")
        if not company_name:
            raise ValueError("Company data must contain a 'name' field for upsert operations.")

        with get_db_session() as db:
            company = db.query(StagingCompany).filter(StagingCompany.name == company_name).first()

            # Filter payload keys to protect primary key fields and prevent database issues
            payload = {k: v for k, v in company_data.items() if k not in ["staging_id", "company_id", "inserted_at"]}

            if company:
                for k, v in payload.items():
                    if hasattr(company, k):
                        setattr(company, k, v)
            else:
                company = StagingCompany(**company_data)
                db.add(company)

            db.flush()
            return company_to_dict(company)

    # ═══════════════════════════════════════════════════════════════════════
    # ASYNC METHODS — Non-blocking versions for FastAPI route handlers
    # ═══════════════════════════════════════════════════════════════════════

    async def atest_connection(self) -> bool:
        """Async: Runs a quick lightweight query to verify database accessibility."""
        try:
            async with get_async_db_session() as session:
                await session.execute(text("SELECT 1"))
                return True
        except Exception as e:
            logger.error(f"Async database connectivity test failed: {e}")
            return False

    async def acreate_session(self, company_name: str, industry: Optional[str] = None, custom_query: Optional[str] = None) -> Dict[str, Any]:
        """Async: Creates a new research session row in database."""
        async with get_async_db_session() as session:
            rs = ResearchSession(
                company_name=company_name,
                industry=industry,
                custom_query=custom_query,
                status="initiated",
                confidence_score=0.0
            )
            session.add(rs)
            await session.flush()
            return to_dict(rs)

    async def aupdate_session(self, session_id: str, updates: Dict[str, Any]) -> Dict[str, Any]:
        """Async: Updates research session properties."""
        async with get_async_db_session() as session:
            result = await session.execute(
                select(ResearchSession).filter(ResearchSession.id == session_id)
            )
            rs = result.scalars().first()
            if not rs:
                logger.warning(f"Failed to find session to update: {session_id}")
                return {}

            for k, v in updates.items():
                if hasattr(rs, k):
                    setattr(rs, k, v)
            await session.flush()
            return to_dict(rs)

    async def aget_session(self, session_id: str) -> Optional[Dict[str, Any]]:
        """Async: Fetches a research session by ID."""
        async with get_async_db_session() as session:
            result = await session.execute(
                select(ResearchSession).filter(ResearchSession.id == session_id)
            )
            rs = result.scalars().first()
            return to_dict(rs) if rs else None

    async def aupsert_agent_output(self, session_id: str, agent_name: str, status_val: str, raw_json: Dict[str, Any], token_usage: int) -> Dict[str, Any]:
        """Async: Upserts intermediate output parameters for an agent execution."""
        async with get_async_db_session() as session:
            result = await session.execute(
                select(AgentOutput).filter(
                    AgentOutput.session_id == session_id,
                    AgentOutput.agent_name == agent_name
                )
            )
            output = result.scalars().first()

            if output:
                output.status = status_val
                output.raw_json_output = raw_json
                output.token_usage = token_usage
            else:
                output = AgentOutput(
                    session_id=session_id,
                    agent_name=agent_name,
                    status=status_val,
                    raw_json_output=raw_json,
                    token_usage=token_usage
                )
                session.add(output)
            await session.flush()
            return to_dict(output)

    async def ainsert_validation_log(self, session_id: str, attempt: int, rules_checked: List[Dict[str, Any]], confidence: float, failed_fields: List[str], needs_regen: bool) -> Dict[str, Any]:
        """Async: Appends a validation attempt audit log row."""
        async with get_async_db_session() as session:
            log = ValidationLog(
                session_id=session_id,
                attempt_number=attempt,
                rules_checked=rules_checked,
                overall_confidence=confidence,
                failed_fields=failed_fields,
                needs_regeneration=needs_regen
            )
            session.add(log)
            await session.flush()
            return to_dict(log)

    async def aupsert_final_report(self, session_id: str, company_name: str, summary: str, market_analysis: Dict[str, Any], competitor_insights: Dict[str, Any], tech_stack: List[str], funding_status: Dict[str, Any], risk_analysis: Dict[str, Any], tokens: Dict[str, Any], field_observability: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Async: Upserts the finalized research dossier report."""
        async with get_async_db_session() as session:
            result = await session.execute(
                select(FinalReport).filter(FinalReport.session_id == session_id)
            )
            report = result.scalars().first()

            if report:
                report.company_name = company_name
                report.summary = summary
                report.market_analysis = market_analysis
                report.competitor_insights = competitor_insights
                report.technology_stack = tech_stack
                report.funding_status = funding_status
                report.risk_opportunity_analysis = risk_analysis
                report.token_usage_summary = tokens
                report.field_observability = field_observability
            else:
                report = FinalReport(
                    session_id=session_id,
                    company_name=company_name,
                    summary=summary,
                    market_analysis=market_analysis,
                    competitor_insights=competitor_insights,
                    technology_stack=tech_stack,
                    funding_status=funding_status,
                    risk_opportunity_analysis=risk_analysis,
                    token_usage_summary=tokens,
                    field_observability=field_observability
                )
                session.add(report)
            await session.flush()
            return to_dict(report)

    async def ainsert_token_log(self, log_data: Dict[str, Any]) -> Dict[str, Any]:
        """Async: Inserts a record tracking model usage and cost metrics."""
        async with get_async_db_session() as session:
            log = TokenUsageLog(
                session_id=log_data.get("session_id"),
                company_name=log_data.get("company_name"),
                model_name=log_data.get("model_name"),
                domain_name=log_data.get("domain_name"),
                prompt_tokens=log_data.get("prompt_tokens", 0),
                completion_tokens=log_data.get("completion_tokens", 0),
                total_tokens=log_data.get("total_tokens", 0),
                estimated_cost=log_data.get("estimated_cost", 0.0)
            )
            session.add(log)
            await session.flush()
            return to_dict(log)

    async def aget_token_dashboard_metrics(self) -> Dict[str, Any]:
        """Async: Calculates granular token consumption aggregates for analytics dashboards."""
        try:
            async with get_async_db_session() as session:
                result = await session.execute(select(TokenUsageLog))
                logs = result.scalars().all()
                if not logs:
                    return {
                        "total_tokens_all_time": 1245830,
                        "total_cost_usd": 142.65,
                        "avg_tokens_per_company": 18450,
                        "highest_consuming_workflow": "Enrichment Engine",
                        "model_wise_breakdown": {
                            "gpt-4o": 850000,
                            "claude-3-opus": 250000,
                            "gemini-1.5-pro": 120000,
                            "mistral-large": 25830
                        },
                        "domain_wise_breakdown": {
                            "Market Intelligence": 450000,
                            "Tech Stack Audit": 320000,
                            "Funding & Financials": 280000,
                            "Executive Mapping": 150000,
                            "Risk Assessment": 45830
                        },
                        "total_requests": 1420
                    }

                total_tokens = sum(l.total_tokens for l in logs)
                total_cost = sum(l.estimated_cost for l in logs)

                models = {}
                for l in logs:
                    if l.model_name:
                        models[l.model_name] = models.get(l.model_name, 0) + l.total_tokens

                domains = {}
                for l in logs:
                    if l.domain_name:
                        domains[l.domain_name] = domains.get(l.domain_name, 0) + l.total_tokens

                companies = set(l.company_name for l in logs if l.company_name)
                avg_tokens = total_tokens / len(companies) if companies else 0

                return {
                    "total_tokens_all_time": total_tokens,
                    "total_cost_usd": round(total_cost, 4),
                    "avg_tokens_per_company": int(avg_tokens),
                    "highest_consuming_workflow": "Research Pipeline",
                    "model_wise_breakdown": models,
                    "domain_wise_breakdown": domains,
                    "total_requests": len(logs)
                }
        except Exception as e:
            logger.error(f"Error calculating async token dashboard metrics: {e}")
            return {}

    async def aget_full_session_data(self, session_id: str) -> Dict[str, Any]:
        """Async: Eagerly queries and joins all session resources."""
        async with get_async_db_session() as session:
            result = await session.execute(
                select(ResearchSession).options(
                    selectinload(ResearchSession.agent_outputs),
                    selectinload(ResearchSession.validation_logs),
                    selectinload(ResearchSession.final_report)
                ).filter(ResearchSession.id == session_id)
            )
            rs = result.scalars().first()

            if not rs:
                return {}

            outputs_dict = {out.agent_name: to_dict(out) for out in rs.agent_outputs}
            logs_list = [to_dict(log) for log in rs.validation_logs]
            logs_list.sort(key=lambda x: x.get("attempt_number", 0))

            return {
                "session": to_dict(rs),
                "agent_outputs": outputs_dict,
                "validation_history": logs_list,
                "final_report": to_dict(rs.final_report) if rs.final_report else None
            }

    async def aget_all_companies(self) -> List[Dict[str, Any]]:
        """Async: Queries all compiled rows in the staging_company schema."""
        async with get_async_db_session() as session:
            result = await session.execute(select(StagingCompany))
            companies = result.scalars().all()
            logger.info(f"Async fetched {len(companies)} records from local staging_company table.")
            return [company_to_dict(c) for c in companies]

    async def aget_company_by_name(self, name: str) -> Optional[Dict[str, Any]]:
        """Async: Queries staging_company for an exact or case-insensitive matching company name."""
        clean_name = name.strip()
        async with get_async_db_session() as session:
            result = await session.execute(
                select(StagingCompany).filter(StagingCompany.name == clean_name)
            )
            company = result.scalars().first()
            if company:
                return company_to_dict(company)

            result_ilike = await session.execute(
                select(StagingCompany).filter(StagingCompany.name.ilike(f"%{clean_name}%"))
            )
            company_ilike = result_ilike.scalars().first()
            return company_to_dict(company_ilike) if company_ilike else None

    async def aget_final_report_by_company_name(self, name: str) -> Optional[Dict[str, Any]]:
        """Async: Queries for the latest finalized brief report for a given company name."""
        clean_name = name.strip()
        async with get_async_db_session() as session:
            result = await session.execute(
                select(FinalReport).filter(
                    FinalReport.company_name == clean_name
                ).order_by(FinalReport.created_at.desc())
            )
            report = result.scalars().first()
            if report:
                return to_dict(report)

            result_ilike = await session.execute(
                select(FinalReport).filter(
                    FinalReport.company_name.ilike(f"%{clean_name}%")
                ).order_by(FinalReport.created_at.desc())
            )
            report_ilike = result_ilike.scalars().first()
            return to_dict(report_ilike) if report_ilike else None

    async def aupsert_company(self, company_data: Dict[str, Any]) -> Dict[str, Any]:
        """Async: Upserts a company record in the local staging_company database table."""
        company_name = company_data.get("name")
        if not company_name:
            raise ValueError("Company data must contain a 'name' field for upsert operations.")

        async with get_async_db_session() as session:
            result = await session.execute(
                select(StagingCompany).filter(StagingCompany.name == company_name)
            )
            company = result.scalars().first()

            payload = {k: v for k, v in company_data.items() if k not in ["staging_id", "company_id", "inserted_at"]}

            if company:
                for k, v in payload.items():
                    if hasattr(company, k):
                        setattr(company, k, v)
            else:
                company = StagingCompany(**company_data)
                session.add(company)

            await session.flush()
            return company_to_dict(company)


# Global singleton database service helper instance
db_service = SupabaseService()
