"""Initial schema setup

Revision ID: 3e2997315605
Revises: 
Create Date: 2026-05-18 04:37:37.144234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.staging_company


# revision identifiers, used by Alembic.
revision: str = '3e2997315605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('custom_query', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_status'), ['status'], unique=False)

    op.create_table('staging_company',
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('incorporation_year', sa.String(length=50), nullable=True),
    sa.Column('nature_of_company', sa.String(length=255), nullable=True),
    sa.Column('headquarters_address', sa.Text(), nullable=True),
    sa.Column('office_count', sa.Integer(), nullable=True),
    sa.Column('employee_size', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_handle', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone_number', sa.String(length=255), nullable=True),
    sa.Column('overview_text', sa.Text(), nullable=True),
    sa.Column('vision_statement', sa.Text(), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('legal_issues', sa.Text(), nullable=True),
    sa.Column('carbon_footprint', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('staging_company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staging_company_name'), ['name'], unique=True)

    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('total_records_checked', sa.Integer(), nullable=False),
    sa.Column('passed_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('overall_quality_score', sa.Float(), nullable=False),
    sa.Column('execution_time_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_outputs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('raw_json_output', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_outputs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_outputs_session_id'), ['session_id'], unique=False)

    op.create_table('company_embeddings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('metadata_text', sa.Text(), nullable=False),
    sa.Column('embedding', app.models.staging_company.SafeEmbeddingVector(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['staging_company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_embeddings_company_id'), ['company_id'], unique=True)

    op.create_table('final_reports',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('market_analysis', sa.JSON(), nullable=True),
    sa.Column('competitor_insights', sa.JSON(), nullable=True),
    sa.Column('technology_stack', sa.JSON(), nullable=True),
    sa.Column('funding_status', sa.JSON(), nullable=True),
    sa.Column('risk_opportunity_analysis', sa.JSON(), nullable=True),
    sa.Column('token_usage_summary', sa.JSON(), nullable=True),
    sa.Column('field_observability', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_reports_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_reports_session_id'), ['session_id'], unique=True)

    op.create_table('token_usage_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_logs_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_logs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_logs_session_id'), ['session_id'], unique=False)

    op.create_table('validation_correction_suggestions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('suggested_value', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['staging_company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_correction_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_correction_suggestions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_correction_suggestions_status'), ['status'], unique=False)

    op.create_table('validation_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('rules_checked', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('failed_fields', sa.JSON(), nullable=True),
    sa.Column('needs_regeneration', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_logs_attempt_number'), ['attempt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_logs_session_id'), ['session_id'], unique=False)

    op.create_table('validation_results_detail',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('expected_condition', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['staging_company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_detail_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_detail_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_detail_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_detail_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_results_detail_status'))
        batch_op.drop_index(batch_op.f('ix_validation_results_detail_run_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_detail_company_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_detail_category'))

    op.drop_table('validation_results_detail')
    with op.batch_alter_table('validation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_validation_logs_attempt_number'))

    op.drop_table('validation_logs')
    with op.batch_alter_table('validation_correction_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_correction_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_validation_correction_suggestions_company_id'))

    op.drop_table('validation_correction_suggestions')
    with op.batch_alter_table('token_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_logs_model_name'))
        batch_op.drop_index(batch_op.f('ix_token_usage_logs_company_name'))

    op.drop_table('token_usage_logs')
    with op.batch_alter_table('final_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_reports_session_id'))
        batch_op.drop_index(batch_op.f('ix_final_reports_company_name'))

    op.drop_table('final_reports')
    with op.batch_alter_table('company_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_embeddings_company_id'))

    op.drop_table('company_embeddings')
    with op.batch_alter_table('agent_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_outputs_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_outputs_agent_name'))

    op.drop_table('agent_outputs')
    op.drop_table('validation_runs')
    with op.batch_alter_table('staging_company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staging_company_name'))

    op.drop_table('staging_company')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_company_name'))

    op.drop_table('research_sessions')
    # ### end Alembic commands ###
