"""add_placement_drives_applications_interviews_results

Revision ID: c91b43462dec
Revises: e5fadb5ce162
Create Date: 2026-05-18 04:55:32.245021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91b43462dec'
down_revision: Union[str, Sequence[str], None] = 'e5fadb5ce162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_drives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('job_role', sa.String(length=100), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('package_lpa', sa.Float(), nullable=True),
    sa.Column('drive_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['staging_company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_drives_company_id'), ['company_id'], unique=False)

    op.create_table('placement_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drive_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_applications_drive_id'), ['drive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_applications_student_id'), ['student_id'], unique=False)

    op.create_table('interview_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location_link', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['placement_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_schedules_application_id'), ['application_id'], unique=False)

    op.create_table('placement_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('offered_package_lpa', sa.Float(), nullable=True),
    sa.Column('offer_letter_path', sa.String(length=500), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['placement_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_results_application_id'), ['application_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_results_application_id'))

    op.drop_table('placement_results')
    with op.batch_alter_table('interview_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_schedules_application_id'))

    op.drop_table('interview_schedules')
    with op.batch_alter_table('placement_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_applications_student_id'))
        batch_op.drop_index(batch_op.f('ix_placement_applications_drive_id'))

    op.drop_table('placement_applications')
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_drives_company_id'))

    op.drop_table('placement_drives')
    # ### end Alembic commands ###
